# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05215a3d1a1dd8648f7c6ee3c333778e5c99cb9115fdf313f1ee79b276008dd32d36817dc60bded89d3eb7d679797096758ae2667c08ff756e234851016296ed

test:
  secret_key_base: 5b3e49d01fe19e183c7c5d4a758352071cf581d1192f9c3c137f99e8c383436f3cc99893bf1fb34a8140c17cfdebfce67e44ea64ba25c85cdee8cb72d5a9512f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
